version: '3.9'
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: always
    ports:
      - 80:80
      - 8081:8080
      - ${SOCIAL_SERVICE_PORT}:${SOCIAL_SERVICE_PORT}
      - ${CONTACT_SERVICE_PORT}:${CONTACT_SERVICE_PORT}
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.network=traefik_proxy"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.social.address=:${SOCIAL_SERVICE_PORT}"
      - "--entrypoints.contact.address=:${CONTACT_SERVICE_PORT}"
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.service=api@internal"
  social-service:
    container_name: social-service
    build:
      dockerfile: social-service/Dockerfile
      context: .
      target: ${ENV}
      args:
        SERVICE_PORT: ${SOCIAL_SERVICE_PORT}
    image: social-service:latest
    networks:
      - proxy
    volumes:
      - ./social-service:/app
    env_file:
      - ./social-service/.env
    labels:
      traefik.enable: true
      traefik.port: ${SOCIAL_SERVICE_PORT}
      traefik.http.routers.social-service.rule: Host(`${SOCIAL_SERVICE_HOST}`)
      traefik.http.routers.social-service.entrypoints: web
  contact-service:
    container_name: contact-service
    build:
      dockerfile: contact-service/Dockerfile
      context: .
      target: ${ENV}
      args:
        SERVICE_PORT: ${CONTACT_SERVICE_PORT}
    image: contact-service:latest
    networks:
      - proxy
    volumes:
      - ./contact-service:/app
    env_file:
      - ./contact-service/.env
    labels:
      traefik.enable: true
      traefik.port: ${CONTACT_SERVICE_PORT}
      traefik.http.routers.contact-service.rule: Host(`${CONTACT_SERVICE_HOST}`)
      traefik.http.routers.contact-service.entrypoints: web

networks:
  proxy:
    name: portfolio-proxy
    driver: bridge
